const express = require("express");
const app = express();

app.use(express.json());

const novelas = [
  {
    id: 1,
    name: "GUERRA SOBERANA VOLANDO LOS CIELOS",
    description:
      "El alma del principal especialista en armas de la Tierra cruzó a un mundo alternativo, se fusionó con los recuerdos del Emperador Marcial Renacimiento, cultivó la Técnica Soberana de la Guerra de los Nueve Dragones y arrasó con toda la oposición con un poder invencible. Capaz de refinar la medicina, capaz de fabricar armas y conoce el arte de la inscripción... ¡Ser hábil en todas las profesiones es el camino de los reyes!",
    categoria: "Accion",
    image:
      "https://novelfull.com/uploads/thumbs/war-sovereign-soaring-the-heaven-e5fb421bc4-2239c49aee6b961904acf173b7e4602a.jpg",
    chapters: {
      1: {
        title: "Capitulo 1",
        contenido:
          "En una habitación de estilo antiguo, Ling Tian se despertó sobresaltado.  ‘No es bueno. ¡He caído en una trampa!  Ni siquiera tuvo tiempo de abrir los ojos mientras reflexivamente golpeaba el suelo con las manos, con la intención de usar la contrafuerza producida para saltar y huir...  ¡Esta fue una reacción instintiva para un miembro destacado de las Fuerzas Especiales!  En el momento en que sus manos tocaron el suelo, un dolor doloroso recorrió su mano como un rayo, junto con un estallido de impotencia.  Ling Tian abrió los ojos mientras su mente temblaba.  ‘Tian, finalmente estás despierto’.  La voz suave y gratamente sorprendida de una mujer llegó a sus oídos.  Ling Tian miró hacia la fuente de la voz y encontró un rostro delicado lleno de amor mirándolo atentamente.  Vio una belleza clásica que era increíblemente hermosa y absolutamente hermosa.  En la mente de Ling Tian, se desarrolló una corriente familiar de recuerdos...  Ling Tian, ciudadano de Hua.  Anteriormente sirvió en la nación de las Fuerzas Especiales Elite Wolf Fang de la División del Ejército de Hua y realizó innumerables actos meritorios a lo largo de su servicio.  Participó en la Competencia Internacional de Fuerzas Especiales, ganó el honor de mejor combatiente individual y fue reconocido como ‘El Rey de los Especialistas en Armas’.  Más tarde, en una misión multinacional de rango SSS, un pequeño error por su parte provocó el sacrificio de un compañero.  Acosado por la culpa, decidió retirarse y abandonó la División Wolf Fang.  Tras jubilarse, no hubo noticias suyas durante algún tiempo. Eligió ir al extranjero y se convirtió en la carta de triunfo de una organización mercenaria de renombre internacional.  ¡Cualquier misión en la que participara tendría una tasa de éxito incomparable del 100%!  Aunque se había retirado de la División Wolf Fang hace muchos años, su corazón todavía estaba con su tierra natal.  Mientras una misión fuera perjudicial para la nación de Hua, no solo rechazaría la misión, sino que también descubriría la identidad de la persona que la emitió y lo masacraría brutalmente. ",
      },
      2: {
        title: "Capitulo 2",
        contenido:
          "A medida que pasó el tiempo, se convirtió en una espina clavada en todas las naciones excepto en la nación de Hua.  A los ojos de las demás naciones, era una bomba de tiempo.  La matanza y el derramamiento de sangre seguirían dondequiera que fuera.  Varios países comenzaron a conspirar contra él, sin escatimar en gastos para contratar asesinos de talla mundial.  Sin embargo, la vida de Ling Tian se volvió más cómoda a medida que pasaban los días y los asesinos desaparecieron en el aire. Al final, ningún asesino estuvo dispuesto a aceptar la ‘Misión Suicida’.  ¡Intentar matar a Ling Tian era lo mismo que suicidarse!  Esta declaración fue universalmente reconocida tanto por el mundo asesino como por el mercenario.  Él, Ling Tian, no solo era un formidable especialista en armas, sino que también era un maestro practicante de Form and Will Boxing que incluso logró cultivar su energía interna.  Rara vez pudo enfrentarse a un oponente en todo el mundo; Incluso en las raras ocasiones en que se encontró con uno, ¡nunca perdió!  No hace mucho, Ling Tian recibió noticias de su corredor de mayor confianza.  R Nation había creado un tipo de arma biológica incolora e insípida. Planeaban transportar el arma a la nación de Hua para llevar a cabo una conspiración atroz.  Naturalmente, Ling Tian no se quedaría de brazos cruzados y dejaría que esto sucediera.  ¡Él tomó acción!  Con la ayuda de su intermediario se localizó la ubicación de las armas biológicas.  Justo cuando logró abrir un camino de sangre y entrar al laboratorio subterráneo, y justo cuando estaba a punto de destruir el lote de armas biológicas… El laboratorio subterráneo de repente se derrumbó, atrapándolo en una jaula completamente sellada.  Cuando vio a los compatriotas R apareciendo fuera de la jaula uno por uno, con armas de fuego en sus manos… Ling Tian lo entendió de inmediato.  Esto era una conspiración… una conspiración contra él.  ¡Fue traicionado por la persona en la que más confiaba!  De lo contrario, con su nivel de astucia, la conspiración de los compatriotas de R nunca habría podido tener éxito. ",
      },
      3: {
        title: "Capitulo 3",
        contenido:
          " Incluso hasta el momento de la muerte, Ling Tian no pudo entenderlo.  ‘Ja, ja, ja, ja…’  Mientras los pensamientos pasaban por su mente, Ling Tian no pudo contenerse y se echó a reír; su estado de ánimo estaba lleno de alegría.   ‘Tian, ¿qué te pasa? No asustes a tu madre’.  La suave voz volvió a sonar, esta vez con un toque de ansiedad.  La mente de Ling Tian estaba sumida en el caos...  Estaba absolutamente seguro de no reconocer a la mujer frente a sus ojos.  Sin embargo, la mirada en los ojos de esta mujer parecía estar llena de sinceridad y sin falsedad alguna, como si estuviera mirando a sus propios parientes.  Justo cuando Ling Tian se estaba preparando para iniciar un debate con esta hermosa mujer, una corriente de recuerdos extraños fluyó en su mente...  Ling Tian sintió como si lo hubiera alcanzado un rayo, completamente estupefacto, como si estuvieran aplicando presión en sus puntos de acupuntura.  Lo único que le complació a Ling Tian fue que este tipo también se llamaba Ling Tian... ‘Duan Ling Tian’.  Duan Ling Tian, 15 años.  Fresh Breeze Town, discípulo de la familia Li con otro apellido.  Su madre, Li Rou, era la novena anciana de la familia Li.  Su padre... en sus recuerdos, para empezar, no existía tal persona.  En el proceso de fusionarse con este segmento de recuerdos extranjeros, Ling Tian encontró la razón por la que Duan Ling Tian resultó gravemente herido y postrado en cama.  Esta mañana, el hijo menor del Séptimo Anciano de la familia Li, Li Xin, insultó a Duan Ling Tian llamándolo hijo bastardo que solo conocía a su madre pero no a su padre.  Duan Ling Tian tuvo un ataque de ira y comenzó a pelear con Lin Xi...  Pero, ¿cómo podría Duan Ling Tian, que ni siquiera había alcanzado la Etapa de Templado Corporal, ser rival para Li Xin, que ya había alcanzado el nivel dos de la Etapa de Templado Corporal? Inmediatamente Li Xin lo hirió gravemente y lo envió al borde de la muerte.  Justo cuando Duan Ling Tian inhaló su último aliento de aire, Ling Tian se apoderó de todo el ser de Duan Ling Tian... incluyendo el cuerpo y los recuerdos de Duan Ling Tian.  Después de fusionarse completamente con los recuerdos extranjeros, Ling Tian suspiró.  Sabía que, a partir de ese momento, usaría la identidad de Duan Ling Tian para integrarse en este mundo extranjero. ",
      },
      4: {
        title: "Capitulo 4",
        contenido:
          " A partir de hoy, él sería Duan Ling Tian y Duan Ling Tian sería él.  ‘Señora, el Patriarca envió algunas medicinas’.  Una voz sonó desde el costado de sus oídos, haciendo que Duan Ling Ting mirara hacia la fuente de la voz.  Una sirvienta entró apresuradamente en la habitación y le entregó el pequeño y exquisito estuche que tenía en las manos a Li Rou.  Una fragancia medicinal flotó en el aire inmediatamente cuando se abrió la pequeña caja.  ‘Tian, ven; Toma esta pastilla medicinal. Madre tratará tus heridas’.  Li Rou sacó una pastilla medicinal de aspecto oscuro del estuche y la guió hasta el frente de la boca de Duan Ling Tian.  Respirando profundamente, Duan Ling Tian abrió la boca y tragó la pastilla.  La píldora se disolvió al entrar en su boca y se convirtió en una corriente cálida cuando entró en su cuerpo.  Posteriormente, Duan Ling Tian notó que Li Rou había puesto su mano sobre su pecho...  Una corriente de corriente helada pasó por su cuerpo, disolviendo la corriente cálida de la píldora y tratando sus heridas.  Una hora más tarde, Li Rou terminó.  Duan Ling Tian notó que la mitad del dolor en su cuerpo había desaparecido, sin ningún tipo de tensión.  Estaba sorprendido.  ¿Lo que acababa de tomar fue una especie de elixir de vida?  Mientras tanto, Duan Ling Tian notó que el rostro de Li Rou estaba pálido, mientras gotas de sudor frío goteaban de su frente. Obviamente, ella gastó demasiada Origin Energy en el tratamiento de sus heridas.  ‘Mamá, ¿estás bien?’  El corazón de Duan Ling Tian se sintió cálido.  Su voz sonaba íntima, sin ningún ápice de artificialidad.  ‘Madre está bien. Sólo necesito descansar un rato’.  Li Rou negó con la cabeza mientras sonreía.  Por el bien de su hijo, gastar este poco de Origin Energy no fue nada.  Media hora más tarde, la sirvienta entró en la habitación y dijo a la ligera: ‘Señora, el Patriarca envió a alguien para preguntar si liberaría al joven maestro Xin ahora. El Patriarca y el Séptimo Anciano todavía están esperando en la Sala de Castigo’.  ‘¿Sueltenlo? ¡Ve y dile a la persona que envió el Patriarca que yo mismo me ocuparé de este asunto!  La expresión gentil y amable en el rostro de Li Rou desapareció por completo, reemplazada por una expresión helada, haciendo que la habitación se sintiera como si la temperatura hubiera bajado ligeramente.   ",
      },
      5: {
        title: "Capitulo 5",
        contenido:
          " El corazón de Duan Ling Tian se agitó.  Nunca pensó que esta mujer, que era tan hermosa como una flor, sería tan protectora...  ‘Mamá, ¿qué fue esa pastilla que me diste antes? Siento que mis heridas casi están curadas’.  Duan Ling Tian se levantó de la cama y estiró ligeramente su cuerpo.  ‘Niño tonto, esa fue una 'píldora de oro para lesiones de grado ocho'‘, Li Rou sonrió levemente.  ¡Píldora de oro para lesiones de octavo grado!  Duan Ling Tian examinó los recuerdos extraños en su mente...  Resultó que incluso dentro de la familia Li de Fresh Breeze Town, solo había dos de estas píldoras de lesiones de oro de grado ocho. Ahora, uno había sido usado contra él, un discípulo con otro apellido.  Parecía que su madre tenía un estatus bastante alto en la familia Li.  ‘Tian, el Patriarca nos está esperando. Vamos.’  Li Rou llevó a Duan Ling Tian a un espacioso patio en Li Family Estate.  Instrumentos de tortura esparcidos por el vasto patio.  Aquí era donde se llevaba a cabo el castigo en la familia Li: ¡el Salón de Castigo!  Era exactamente mediodía y el sol ardía en lo alto del cielo...  Los alrededores del Salón de Castigo estaban llenos de gente. Los discípulos de la familia Li habían venido a ver el espectáculo.  En medio del patio, un joven estaba atado a un pilar bajo el sol abrasador con dos hombres de mediana edad a su lado.  El hombre bizco de mediana edad del lado derecho tenía una expresión de rabia cuando notó la llegada de Duan Ling Tian y su madre.  ",
      },
      6: {
        title: "Capitulo 6",
        contenido:
          "‘Duan Ling Tian ha llegado... ¡La preciosa píldora de oro de grado ocho para lesiones de la familia tiene un efecto tan fuerte!’  ‘Sí, estuve allí cuando se llevaron a Duan Ling Tian, medio muerto, pero ahora, después de tomar la píldora de oro de grado ocho para lesiones, ha vuelto a estar lleno de vigor y vitalidad’.  ‘Por lo general, Lin Xin simplemente intimidaba casualmente a Duan Ling Tian y el Noveno Anciano no decía nada al respecto. Sin embargo, esta vez infligió heridas tan graves que Duan Ling Tian casi muere... Por supuesto, el Noveno Anciano se pondrá furioso.  ……  Uno por uno, los discípulos de la familia Li comenzaron a susurrar entre ellos cuando notaron la llegada de Li Rou y Duan Ling Tian.  ‘¡Patriarca!’  Li Rou llevó a Duan Ling Tian para saludar al hombre de mediana edad de la izquierda.  ‘Noveno Anciano, con respecto a los asuntos de hoy, mi hijo Li Xin estaba equivocado. Por otro lado, tu hijo ahora está bien y sin embargo mi hijo ha estado ardiendo bajo el sol toda la tarde. ¿Podemos decepcionarlo ahora?  En este momento, el hombre bizco de mediana edad, el Séptimo Anciano de la Familia Li, Li Kun, tenía una expresión oscura.  ¿Quién hubiera pensado que Li Rou ni siquiera se molestaría en responderle y lo ignoraría directamente?  Li Rou llevó a Duan Ling Tian frente al atado Li Xin.  ‘¡Tian, ahora es el momento de pagarle de la misma manera que te lastimó antes!’",
      },
    },
    categorias: [{ accion: "Accion" }, { romance: "Romance" }],
  },
  {
    id: 2,
    name: "LEVEL UP LEGACY",
    description:
      "Arthur Silvera miraba fijamente el holograma que tenía delante, sin saber qué estaba pasando. Había despertado esta habilidad nunca vista, y estaba aterradoramente fastidiado. La runa dorada que tenía delante flotaba sin inmutarse. Tal y como describía su Legado, era una runa para absorber estadísticas de los enemigos que matara. Esto, por sí mismo, era una habilidad absurda. Sin embargo, era una de muchas. El Legado que ha despertado le convirtió de un sucio a.... un creador. En un mundo donde la tecnología moderna se fusionó con la magia, los gremios, las mazmorras y los mechas son ahora todo lo que le importa al mundo. Los monstruos acechan en lo más profundo del mundo, conectando con reinos desconocidos. Las superpotencias compiten por la supremacía, creando una rueda sin fin que aplasta a cualquiera que flaquee. Y en una de las ciudades ordinarias de este mundo, un joven corriente se convierte en el más extraordinario.",
    categoria: "Ciencia ficcion",
    image:
      "https://jesusful.com/ebooks/wp-content/uploads/2023/03/Level-Up-Legacy.jpg",
    chapters: {
      1: {
        title: "Capitulo 1",
        contenido:
          "Tenía grandes esperanzas porque leyó los comentarios y todos decían que el trabajo era demasiado arriesgado. Por supuesto, no era que fuera valiente o imprudente. Estaba en un estado mucho peor llamado desesperación.  La noche fue larga y Arthur tardó varias horas en investigar la mazmorra de la Avaricia. Fue una de las mazmorras de cuarta generación que aparecieron después de que se estableció la unión federal de Yalveran. La mazmorra apareció después de que se produjo una fusión hace medio año.  Desde entonces, varios sindicatos han intentado conquistarlo, sin éxito. Se afirmó que la mazmorra era el siguiente paso para la humanidad, alentando a guerreros y magos a desafiarla. Después de que surgieron varias bajas, se descubrió que esta mazmorra era una de las Mazmorras de los Pecados, lo que causó un gran revuelo en el mundo.  ‘Ok. Mañana a las 11 a.m., mesa 36. El pago sería de 50$ la hora’.  El contraste de su largo mensaje y lenguaje cortés con la respuesta fue patético, pero la respuesta de todos modos lo emocionó. La emoción pronto fue reemplazada por el miedo.  Ser porteador estaba en la lista de los trabajos más riesgosos para los no despiertos, si no el primero. Había muchos preparativos que hacer, pero Arthur revisó su cuenta bancaria y suspiró. Tuvo que irse con las manos vacías.  ***  Al día siguiente, a las 10:45 a. m., Arthur estaba frente a la entrada del calabozo. Cada mazmorra tenía un vestíbulo para que los guerreros y magos se reunieran y mantuvieran reuniones estratégicas antes de aventurarse en la mazmorra.  Caminó hasta la mesa 36, donde pudo ver a varias personas sentadas. Eran cinco en total; tres vestían armadura completa mientras que los otros dos vestían túnicas. Las tres personas que llevaban armadura eran dos hombres y una mujer, esta última vestía una armadura ligera.",
      },
      2: {
        title: "Capitulo 2",
        contenido:
          "Las personas que vestían túnicas eran un hombre cadavérico y una mujer pequeña. El grupo parecía tener principalmente veintitantos años, mientras que un guerrero con una maza en el cinturón era de mediana edad.  ‘H...Hola, soy Arthur Silvera, el portero’. Arthur se armó de valor y siguió adelante, a pesar de sentirse intimidado. Si bien también era el más débil, ser el más joven hacía que su confianza en sí mismo se escondiera en lo más profundo de su ser, sin atreverse a mostrarse.  La charla cesó por un segundo y todos volvieron sus ojos hacia él, escrutándolo. Al ser examinado así, Arthur jugueteó nerviosamente con su pulgar derecho.  ‘Hola, soy Alan, hablé contigo ayer’. El guerrero maza, conocido como Alan, se adelantó y le estrechó la mano. El cálido gesto de respeto envió alivio a la mente de Arthur, e intercambió algunas bromas.  Sin embargo, el resto del equipo mostró poco interés en él y reanudaron su charla sobre los monstruos que los esperaban dentro, las últimas armas y guerreros y magos famosos. La única excepción fue el hombre delgado que vestía una bata, quien le sonrió y asintió con la cabeza.  Arthur no pensó en ello ya que estaban una legua por encima de él en estatus, por lo que se sentó en un asiento no demasiado lejos ni demasiado cerca del resto.  ‘Como todos saben, hoy no iremos más allá de la tercera capa. He ejecutado nuestro poder de combate a través de una aplicación de analista de mazmorras y indicó que podemos manejarlo, excepto algunos monstruos difíciles que debemos evitar. Eso no Eso no significa que podamos estar relajados, siempre se sabe que las mazmorras de Sins lo son, además de ser de alto riesgo y alta recompensa por su irregularidad’.",
      },
      3: {
        title: "Capitulo 3",
        contenido:
          " Alan continuó su sesión informativa y duró hasta el mediodía. A pesar de que esta información era irrelevante, Arthur aguzó el oído y los escuchó en caso de que resultaran útiles en el futuro.  Al mediodía, Alan pidió algo de almuerzo en el restaurante del calabozo para que el equipo comiera antes de partir. Arthur comía muy poco ya que no estaba despierto, por lo que tenía un metabolismo más bajo. No había baños en el calabozo, por lo que tenía que tener cuidado con sus necesidades.  ***  El equipo tenía cuatro miembros además de su líder, Alan, a quien Arthur consideró un líder típico. De las conversaciones que escuchó Arthur, dedujo lo siguiente.   Primero estaba la persona más llamativa, extravagante y sociable, Juan Keizer, el otro guerrero junto a Alan. Hablaba mucho, con una gran caja parlanchina además de su prominente barriga. Sin embargo, era bastante alto, casi más que Alan.  De pie junto al hombre, Arthur empequeñecía, que medía 173 cm de altura y era relativamente delgado. A pesar de tener una conducta amistosa, Juan no le dedicó una mirada a Arthur y lo trató como si fuera aire.  El otro personaje era la persona que respondía al parloteo incesante de Juan, la guerrera Beatrice Faure, una mujer con músculos prominentes y una constitución más grande que la de Arthur, que también se alzaba sobre él. Parecía familiarizada con Juan, y los dos hablaron cómodamente, y Alan también compartió algunas palabras con ellos.  La persona que más le gustaba a Arthur era el chico delgado y pálido que hablaba un poco con él, aunque en su mayoría eran charlas ociosas. No obstante, Arthur se sintió agradecido por la consideración que había mostrado.",
      },
      4: {
        title: "Capitulo 4",
        contenido:
          "A partir de sus conversaciones, Arthur descubrió que este joven, llamado Yuran Evel, tenía un estilo de lucha poco común pero infame llamado Magic Gunman.  Lucharon usando armas de poder mágico desde lejos, utilizando maná comprimido básico para infligir daño. Al ver el arma de Yuran, Arthur quedó asombrado al encontrarse con un pistolero mágico por primera vez.    La última persona fue la pequeña joven, que parecía mayor que él, pero no mucho. No supo su nombre ya que ella no había dicho una palabra en todo el tiempo.  El grupo se dirigió hacia la entrada de la mazmorra cuando el reloj sonó al mediodía y Arthur se sintió cansado con solo ver las oleadas de gente entrando y saliendo. Muchos resultaron heridos, algunos murieron.    Arthur se preguntó si terminaría como el primero o el segundo, tal vez ninguno de los dos. Puede regresar sano y salvo, o nunca podrá regresar.  Sacudió la cabeza como si eso fuera a alejar esos pensamientos. Después de confirmar la identidad de los exploradores, término para las personas que se aventuran a otros mundos, la seguridad les permitió entrar.  Por supuesto, Arthur tuvo que firmar un Acuerdo de Liquidación de Responsabilidad, aclarando la responsabilidad en caso de que muriera.  Al atravesar el portal, el mundo se retorció y su visión se desvió antes de encontrarse en una gran sala subterránea llena de exploradores de todas las razas y culturas.  Al ser una de las Mazmorras de los Pecados, la Avaricia tenía una gran reputación. Incluso se la llamó 'La Puerta del Dragón' porque uno puede saltar sobre ella y ser un dragón entre los hombres, aunque la mayoría fracasaría. Arthur nunca se vio a sí mismo como un hombre digno de convertirse en dragón, pero no pudo evitar desear ser único de alguna manera.",
      },
    },
    categorias: [
      {cienciaficcion: "Ciencia ficcion"},
      {romance: "Romance"}
    ]
  },
  {
    id: 3,
    name: "SHADOW SLAVE",
    description:
      "Sunny creció en la pobreza y nunca esperó nada bueno de la vida. Sin embargo, ni siquiera él esperaba ser elegido por el Conjuro de la Pesadilla y convertirse en uno de los Despertados, un grupo de élite dotado de poderes sobrenaturales. Transportado a un mundo mágico en ruinas, se encontró enfrentado a terribles monstruos -y a otros Despertados- en una mortal batalla por la supervivencia. Y lo que es peor, el poder divino que recibió tenía un efecto secundario pequeño pero potencialmente mortal...",
    categoria: "Accion",
    image: "https://m.media-amazon.com/images/I/515fsT6ty4L._SY466_.jpg",
    chapters: {
      1: {
        title: "Capitulo 1",
        contenido:
          "Un joven de aspecto frágil, piel pálida y ojeras estaba sentado en un banco oxidado frente a la comisaría. Estaba sosteniendo una taza de café en sus manos; no el tipo sintético barato al que las ratas de los barrios marginales como él tenían acceso, sino el verdadero. Esta taza de café de origen vegetal, normalmente disponible sólo para ciudadanos de mayor rango, le había costado la mayor parte de sus ahorros. Pero ese día en particular, Sunny decidió darse un capricho.  Después de todo, su vida estaba llegando a su fin.  Disfrutando del calor de la lujosa bebida, levantó la copa y saboreó el aroma. Luego, tentativamente, tomó un pequeño sorbo... e inmediatamente hizo una mueca.  ‘¡Ah! ¡Qué amargo!’  Sunny miró intensamente la taza de café, suspiró y se obligó a beber un poco más. Amargo o no, estaba decidido a obtener el valor de su dinero: al diablo con sus papilas gustativas.  ‘Debería haber comprado un trozo de carne de verdad. ¿Quién hubiera pensado que el café de verdad es tan repugnante? Bueno. Al menos me mantendrá despierto’.  Miró a lo lejos, se quedó dormido y luego se abofeteó para despertar.  ‘Tsk. Qué estafa.’  Sacudiendo la cabeza y maldiciendo, Sunny terminó el café y se levantó. Los ricos que vivían en esta parte de la ciudad pasaban corriendo por el pequeño parque de camino al trabajo, mirándolo con expresiones extrañas. Luciendo demacrado con su ropa barata y por la falta de sueño, enfermizamente delgado y pálido, Sunny realmente estaba fuera de su lugar aquí.",
      },
      2: {
        title: "Capitulo 2",
        contenido:
          "Además, todos parecían muy altos. Mirándolos con un poco de envidia, arrojó la taza a un contenedor de basura.  .a mí  ‘Supongo que eso es lo que te harían tres comidas completas al día’.  La taza no cayó al contenedor por un amplio margen y cayó al suelo. Sunny puso los ojos en blanco con exasperación, se acercó y lo recogió antes de tirarlo con cuidado a la basura. Luego, con una leve sonrisa, cruzó la calle y entró en la comisaría.  En el interior, un oficial de aspecto cansado le dirigió una rápida mirada y frunció el ceño con evidente disgusto.  ‘¿Estás perdido, muchacho?’  Sunny miró a su alrededor con curiosidad y notó placas de armadura reforzadas en las paredes y nidos de torretas mal escondidos en el techo. El oficial también parecía desaliñado y mezquino. Al menos las comisarías de policía siguen siendo las mismas donde quiera que vayas.  ‘¡Oye! ¡Te estoy hablando!’  Sunny se aclaró la garganta.  ‘UH no.’  Luego se rascó la nuca y añadió:  ‘Como lo exige la Tercera Directiva Especial, estoy aquí para entregarme como portador del Hechizo de Pesadilla’.  La expresión del oficial cambió instantáneamente de irritada a cautelosa. Miró al joven una vez más, esta vez con penetrante intensidad.  ‘¿Estás seguro de que estás infectado? ¿Cuándo empezaste a mostrar síntomas?’  Sunny se encogió de hombros.  ‘¿Hace una semana?’  El oficial palideció visiblemente.  ‘Mierda.’  Luego, con un movimiento apresurado, presionó un botón en su terminal y bramó:  ‘¡Atención! ¡Código Negro en el lobby! ¡Repito! ¡CÓDIGO NEGRO!’  ***  El hechizo Nightmare apareció por primera vez en el mundo hace unas décadas. En aquel entonces, el planeta apenas comenzaba a recuperarse de una serie de desastres naturales devastadores y posteriores guerras por recursos.  Al principio, no llamó mucho la atención la aparición de una nueva enfermedad que provocaba que millones de personas se quejaran de fatiga constante y somnolencia. Pero cuando empezaron a caer en un letargo antinatural, sin señales de despertar incluso días después, los gobiernos finalmente entraron en pánico. Por supuesto, para entonces ya era demasiado tarde; aunque una respuesta temprana no hubiera podido marcar ninguna diferencia.  Cuando los infectados empezaron a morir mientras dormían y sus cadáveres se convirtieron en monstruos, nadie estaba preparado.",
      },
      3: {
        title: "Capitulo 3",
        contenido:
          "Nightmare Creatures rápidamente abrumó a los ejércitos nacionales, hundiendo al mundo en un caos total.  Nadie sabía qué era el hechizo, qué poderes poseía y cómo combatirlo.  Al final, fueron los Despertados (aquellos que sobrevivieron a las primeras pruebas del Hechizo y regresaron con vida) quienes pusieron fin a su alboroto. Armados con habilidades milagrosas obtenidas en sus Pesadillas, restauraron la paz y crearon una apariencia de un nuevo orden.  Por supuesto, fue sólo la primera de las catástrofes provocadas por el Hechizo. Pero en lo que a Sunny concernía, nada de eso tenía nada que ver con él, es decir, no hasta hace unos días, cuando comenzó a tener problemas para mantenerse despierto.   Para una persona promedio, ser elegido por el Hechizo era tanto un riesgo como una oportunidad. Los niños aprendieron habilidades de supervivencia y técnicas de lucha en la escuela, ante la remota posibilidad de infectarse. Las familias acomodadas contrataban tutores privados para entrenar a sus hijos en todo tipo de artes marciales. Aquellos de los clanes Despertados incluso tuvieron acceso a poderosos legados, ejerciendo Memorias y Ecos heredados en su primera visita al Reino de los Sueños.  Cuanto más rica fuera tu familia, mayores serían tus posibilidades de sobrevivir y convertirte en un Despertado.  Pero para Sunny, que no tenía familia de la cual hablar y pasaba la mayor parte de su tiempo buscando comida en lugar de ir a la escuela, ser elegido por el Hechizo no presentaba ninguna oportunidad. Para él, era básicamente una sentencia de muerte.  ***  Unos minutos más tarde, Sunny bostezaba mientras varios policías estaban ocupados inmovilizándolo. Pronto lo ataron a una silla voluminosa que parecía una extraña mezcla entre una cama de hospital y un dispositivo de tortura. La habitación en la que se encontraban estaba situada en el sótano de la comisaría, con gruesas paredes blindadas y una puerta acorazada de aspecto formidable.",
      },
      4: {
        title: "Capitulo 4",
        contenido:
          "Otros agentes estaban parados cerca de las paredes, con rifles automáticos en la mano y expresiones sombrías en sus rostros.  A Sunny no le importaban demasiado. Lo único en lo que podía pensar era en cuánto quería dormir.  Finalmente, la puerta de la bóveda se abrió y entró un policía de cabello gris. Tenía un rostro experimentado y ojos severos, parecía alguien que había visto muchas cosas terribles en su vida. Después de comprobar las correas, el policía miró rápidamente su reloj de pulsera y luego se volvió hacia Sunny:  ‘¿Cómo te llamas, niño?’  Sunny parpadeó un par de veces, tratando de concentrarse, pero luego se movió incómodamente.  ‘Sin sol’.  El viejo policía arqueó una ceja.  ‘¿Sin sol? Ese es un nombre extraño.’  Sunny intentó encogerse de hombros, pero se encontró incapaz de moverse.  ‘¿Qué tiene de extraño? Al menos tengo un nombre. En las afueras, no todo el mundo tiene uno’.  Después de otro bostezo, añadió:  ‘Es porque nací durante un eclipse solar. Mi mamá tenía un alma poética, ¿sabes?’  Es por eso que recibió este nombre extraño y su hermana pequeña se llamaba Rain… al menos cuando todavía vivía con ellos. No sabía si era resultado de la imaginación poética o de simple pereza.  El viejo policía gruñó.  ‘¿Quieres que me comunique con tu familia?’  Sunny simplemente negó con la cabeza.  ‘No hay nadie. No te molestes.’  Por un segundo, hubo una expresión sombría en el rostro del policía. Entonces su expresión se volvió seria.  ‘Muy bien, Sunless. ¿Cuánto tiempo puedes permanecer despierto?’  ‘Uh... no mucho.’  El policía suspiró.  ‘Entonces no tenemos tiempo para el procedimiento completo. Intenta resistir lo más que puedas y escúchame con mucha atención. ¿Está bien?’  Sin esperar respuesta, añadió:  ‘¿Cuánto sabes sobre el hechizo Pesadilla?’  Sunny le dirigió una mirada inquisitiva.  ‘¿Tanto como cualquiera, supongo? ¿Quién no sabe sobre el hechizo?’  ‘No las cosas elegantes que ves en los dramas y escuchas en las transmisiones de propaganda. Quiero decir, ¿cuánto sabes realmente?’  Esa fue una pregunta difícil de responder.  ‘¿No entro simplemente al Reino de los Sueños, mato algunos monstruos para completar la Primera Pesadilla, recibo poderes mágicos y me convierto en un Despertado?’",
      },
      5: {
        title: "Capitulo 5",
        contenido:
          "El viejo policía negó con la cabeza.  ‘Escucha atentamente. Una vez que te duermas, serás transportado dentro de tu Primera Pesadilla. Las pesadillas son pruebas creadas por el Hechizo. Una vez dentro, te encontrarás con monstruos, claro, pero también conocerás personas. Recuerda: no son reales. Son sólo ilusiones conjuradas para ponerte a prueba’.  ‘¿Cómo lo sabes?’  El policía se limitó a mirarlo.  ‘Quiero decir, nadie entiende qué es el hechizo y cómo funciona, ¿verdad? Entonces, ¿cómo sabes que no son reales?’  ‘Puede que tengas que matarlos, chico. Así que hazte un favor y piensa en ellos como ilusiones’.  ‘Oh.’  El viejo policía esperó un segundo, luego asintió y continuó.  ‘Muchas cosas sobre la Primera Pesadilla dependen de la suerte. Generalmente, no debería ser abrumadoramente difícil. La situación en la que te encuentras, las herramientas que tienes a tu disposición y las criaturas que tienes que derrotar deben estar dentro del rango de tus habilidades, al menos. Después de todo, el hechizo establece pruebas, no ejecuciones. Estás un poco en desventaja debido a... bueno... tus circunstancias. Pero los niños de las afueras son duros. No te rindas todavía. ‘   ‘Uh-uh.’  Sunny tenía cada vez más sueño. Se estaba volviendo difícil seguir la conversación.  ‘Acerca de esos ‘poderes mágicos’ que mencionaste... de hecho los recibirás si sobrevives hasta el final de la Pesadilla. Cuáles serán esos poderes, exactamente, depende de tu afinidad natural y de lo que hagas durante la prueba. Pero algunos de Estará a vuestra disposición desde el primer momento...’  La voz del viejo policía sonaba cada vez más distante. Los párpados de Sunny estaban tan pesados que luchaba por mantener los ojos abiertos.  ‘Recuerda: lo primero que debes hacer una vez dentro de la Pesadilla es comprobar tus Atributos y tu Aspecto.",
      },
      6: {
        title: "Capitulo 6",
        contenido:
          "Si consigues un Aspecto orientado al combate, algo así como un Espadachín o un Arquero, las cosas serán más fáciles. Si está reforzado por un Atributo físico, entonces eso es aún mejor. Los Aspectos de Combate son los más comunes, por lo que la probabilidad de recibir uno es alta’.  La habitación blindada se estaba volviendo cada vez más oscura.  ‘Si tienes mala suerte y tu Aspecto no tiene nada que ver con el combate, no te desesperes. Los Aspectos de brujería y utilidad son útiles a su manera, sólo tendrás que ser inteligente al respecto. Realmente no hay Aspectos inútiles. Bueno, casi. Así que haz todo lo que esté a tu alcance para sobrevivir’.  ‘Si sobrevives, estarás a medio camino de convertirte en un Despertado. Pero si mueres, abrirás una puerta para que aparezca una Criatura Pesadilla en el mundo real. Lo que significa que mis colegas y yo tendremos que lidiar con eso. Así que... por favor no mueras, Sunless’.  Ya medio dormida, Sunny se sintió un poco conmovida por las palabras del policía.  ‘O, al menos, trata de no morir de inmediato. El Despertado más cercano no podrá llegar aquí hasta dentro de unas horas, así que te agradeceríamos mucho que no nos hagas luchar contra esa cosa nosotros mismos...’  '¿Qué?'  Con ese último pensamiento, Sunny finalmente cayó en un sueño profundo.  Todo se volvió negro.  Y entonces, en la oscuridad, sonó una voz levemente familiar:  [¡Aspirante! Bienvenido al hechizo de pesadilla. Prepárese para su primera prueba…] ",
      },
    },
    categorias: [
      {accion: "Accion"},
      {aventura: "Aventura"}
    ]
  },
  {
    id: 4,
    name: "CRAZY DETECTIVE",
    description:
      "Un pequeño rufián que luchaba temerariamente sin moral ni fondo viajó accidentalmente en el tiempo al espacio paralelo y se convirtió en agente del Equipo de Investigación de Casos Clave. El enorme cambio de identidad le hizo sembrar el caos en la comisaría. Sin embargo, un extraño sistema milagroso le ayudó a resolver repetidamente casos misteriosos, ¡convirtiéndole en un insolente detective rufián!",
    categoria: "Comedia",
    image:
      "https://vipnovel.com/wp-content/uploads/2019/03/Crazy-Detective-193x278.jpg",
    chapters: {
      1: {
        title: "Capitulo 1",
        contenido:
          "‘¿Eh? ¿Dónde está mi tatuaje?’  Zhao Yu se arremangó y se sorprendió al ver sus dos brazos, que eran blancos e inmaculados. Anteriormente, estaban cubiertas por un tatuaje de dos Dragones Orientales, dibujados por uno de los tatuadores más famosos de la zona. Parecían intimidantes, por decir lo menos.  Pero... ¿dónde estaban ahora?   Zhao Yu levantó la cabeza y se encontró sentado en una oficina bien iluminada que estaba dividida en muchos cubículos pequeños.  En ese momento, la oficina estaba en un estado de caos: teléfonos sonando sin parar, documentos volando y una avalancha de oficinistas corriendo por el pasillo, cada uno de ellos con ansiedad y exasperación escritas en sus rostros.  ’¡Está bien, está bien, reúnanse todos!’ Un hombre de mediana edad vestido con una chaqueta marrón apareció y llamó la atención de todos. ‘El líder del equipo Qu Ping ahora nos describirá la situación con respecto a los casos de violación con Taser. ¡Esta noche nos mudaremos, así que todos escuchen atentamente!’  Otra persona rápidamente detuvo una pizarra que estaba llena de palabras, junto con muchas imágenes publicadas en ella.  Al escuchar el anuncio, muchos trabajadores se apiñaron rápidamente alrededor de la pizarra, acercando sillas cuando fuera conveniente antes de sentarse y mirar atentamente.  En cuanto a Zhao Yu, simplemente permaneció en su propio asiento.  En ese momento, todavía estaba en estado de shock. Zhao Yu se tocó la oreja derecha, ¡perfectamente intacta! Según recordaba, su oreja derecha debería haberse partido en dos durante una pelea con algún enano.  Zhao Yu deseaba poder ver su propio rostro con un espejo o algo así. Miró a su alrededor y sus ojos se posaron en una fotografía que estaba sobre el escritorio de la oficina. La foto mostraba a un hombre joven y apuesto vestido con uniforme de policía, ¡pero el hombre era exactamente igual a él!  ¡Mierda!  El shock finalmente pasó y el hombre sintió que recuerdos extraños inundaban su mente. Zhao Yu finalmente se dio cuenta: ¿Podría ser? Que se había encontrado con el legendario... ¡¿Mind Cross Over?!  Todavía podía recordar claramente que anteriormente era el principal hombre fuerte de la mafia Qing Long, un verdadero rufián hasta los huesos. Aunque su nombre real era Zhao Yu, todos lo llamaban King Fighter Zhao.  ",
      },
      2: {
        title: "Capitulo 2",
        contenido:
          "¿Qué pasó justo antes?  ¡Jesucristo!  Lo que Zhao Yu finalmente recordó fue un shock: ¡ya había sido condenado a muerte por inyección letal!  Los recuerdos regresaron con mayor claridad ahora: cuando la medicina entró lentamente en su cuerpo y el miedo que se extendía lentamente con ella. Estaba murmurando algunos viejos dichos: ‘Más vale una muerte honorable que vivir como un perro...’  Pero, a mitad de camino de sus murmullos, ¿cómo apareció de repente aquí?  ¿Podría realmente haber cruzado a otro cuerpo?  Fue tan repentino; no hubo advertencias ni señales, ni siquiera reencarnación en un bebé.  Con nuevos recuerdos entrando en su mente, se sorprendió al darse cuenta de que no sólo todavía residía en el mundo normal, sino que su identidad actual era la de investigador de la Unidad de Investigación de Casos Clave. En otras palabras, ¡era un oficial de policía!  Entonces, donde estaba sentado era la oficina de una comisaría.  Jesucristo.  Zhao Yu no podía creer lo que veía, desde un rufián callejero hasta un miembro de la Unidad de Investigación de Casos Clave, ¿cómo podría ser esto? El contraste le hizo girar la cabeza.  El hombre se pasó una mano por la cabeza; Anteriormente había tenido muchas heridas con cuchillos en la cabeza que le arruinaron la línea del cabello. Eso ha llevado a su calvicie, tanto por conveniencia como por intimidación. Pero ahora poseía el pelo largo y negro azabache, presentando la imagen de un joven apuesto.  ‘Todos, desde el día 12 de este mes, nuestra ciudad ha tenido tres casos de incidentes de violación con Taser’. En ese momento, una investigadora con cabello corto y ojos grandes estaba informando a todos sobre la situación que rodeaba su misión.  Zhao Yu rápidamente encontró a la investigadora en su memoria: ella era la líder del equipo de la Unidad de Investigación de Casos Clave, Equipo B. A pesar de su juventud, poseía una mente aguda y nervios increíbles, lo que contribuía a su alta tasa de éxito en la resolución de crímenes. La mujer también era increíblemente popular entre los superiores. Por lo general, ella dirigía todos los casos que requerían la cooperación total del equipo.  ",
      },
      3: {
        title: "Capitulo 3",
        contenido:
          " ‘Las víctimas siempre han sido mujeres jóvenes escasamente vestidas, generalmente con algunos hábitos problemáticos’, comenzó su presentación la líder del equipo Qu Ping. ‘Las escenas del crimen generalmente eran lugares como bares y similares. Todos los crímenes se cometieron después de la medianoche’.   ‘Según la descripción de nuestra víctima, el perpetrador primero la siguió hasta un callejón vacío, luego la dejó inconsciente con una descarga Taser antes de proceder a violarla. Después del acto, el perpetrador orinó sobre la víctima’.  Al escuchar la palabra ‘orinar’, toda la multitud se quedó en silencio.  ‘Hemos realizado pruebas en la muestra de orina’, continuó Qu Ping, ‘y hemos llegado a la conclusión de que los tres casos fueron realizados por la misma persona. Además, cuando la tercera víctima se despertó en medio del acto criminal, logró ‘Para rascar la cara del perpetrador durante la lucha que siguió, también hemos obtenido muestras de sangre’.  El líder del equipo, Qu Ping, todavía estaba explicando la situación frente a la pizarra blanca cuando el anterior hombre de mediana edad que vestía la chaqueta marrón de repente giró la cabeza hacia Zhao Yu. El hombre agitó la mano distraídamente y ordenó: ‘Oye, chico, esta noche definitivamente trabajaremos horas extras. ¿Por qué no corres y nos traes un poco de café?’.  Zhao Yu lanzó una mirada al hombre; era el vicecapitán de la Unidad de Investigación de Casos Clave, Liu Changhu. Durante la pasantía de Zhao Yu aquí, el hombre a menudo intimidaba a Zhao Yu, obligándolo a hacer trabajos de baja categoría más como un sirviente que cualquier otra cosa.  Además, el Zhao Yu de este mundo no era un rufián o un luchador, sino un chico de voluntad débil que recientemente había completado su pasantía para convertirse en policía de pleno derecho. No solo Liu Changhu, sino muchos otros compañeros de trabajo más experimentados a menudo también se burlaban de él, dándole trabajo que obviamente no era su responsabilidad. ",
      },
      4: {
        title: "Capitulo 4",
        contenido:
          "‘¡Oye! ¡Date prisa!’ La sonrisa de Liu Changhu se desvaneció cuando vio la falta de reacción de Zhao Yu. ‘¿No me escuchaste? ¿Por qué estás distraído?’  Este Zhao Yu ahora ya no era solo el cobarde que solía ser. ¿Cómo podía empezar a dejar que lo empujaran? El hombre golpeó fuertemente la mesa con las manos y se levantó con un movimiento rápido.  Su acción repentina sorprendió a Liu Changhu, incluso el líder del equipo Qu Ping no pudo evitar hacer una pausa y girarse para mirarlo.  ‘¡Yo-yo lo haré en su lugar!’  Nadie esperaba la interrupción cuando una voz femenina parecida a una campana sonó mientras el equipo miraba a Zhao Yu. Todos observaron cómo apareció a la vista una mujer ligeramente gordita, con una cola de caballo y un par de anteojos enormes.  El nombre de la niña era Li Beini, una nueva pasante en la Unidad de Investigación de Casos Clave. Desafortunadamente, ella también estaba un poco ansiosa. Ni siquiera había pasado un mes desde que comenzó, pero ya estaba perdidamente enamorada de Zhao Yu.  Sin embargo, no fue una gran sorpresa. A pesar de que la débil personalidad de Zhao Yu lo convertía en un blanco constante de acoso, era agradable a la vista, por decir lo menos: 5' 10'' de altura, elegante, joven y guapo. El hombre era definitivamente del tipo que llama la atención en la calle.  Cuando Li Beini vio que la persona que le gustaba se convertía en el objetivo del ataque verbal, rápidamente dio un paso adelante para ayudar: ‘¡Vicecapitán Liu, yo iré en su lugar! Todavía soy pasante, este tipo de tareas eran mías para empezar’. !’  La niña le dedicó una sonrisa a Zhao Yu antes de irse al vestíbulo a preparar café.  Al ver a la chica irse, Liu Changhu le lanzó a Zhao Yu una mirada enojada antes de darse la vuelta. Zhao Yu también se dio cuenta de que esta no era la mejor situación para desatar su ira y se calmó lo suficiente como para sentarse. Todavía estaba considerando toda la situación. ",
      },
      5: {
        title: "Capitulo 5",
        contenido:
          "A pesar de su transición, sus recuerdos eran muy claros, porque hace sólo unos minutos estaba en el corredor de la muerte.  El de la vida anterior fue procesado por asesinato, aunque Zhao Yu sabía que había sido incriminado. La víctima era el jefe de un conglomerado inmobiliario. Zhao Yu solo estaba siguiendo las órdenes de los superiores de maltratarlos un poco, pero no había forma de que pudiera haber causado su muerte.  Además, incluso si hubiera sido muerte por agresión, habría sido homicidio involuntario. ¡No había manera de que fuera procesado como asesinato! Por lo tanto, ¡su sentencia de muerte se debió claramente a alguna influencia externa!  Al recordar tanto, Zhao Yu no pudo evitar la ira que ardía dentro de él. Sus nudillos crujieron con fuerza mientras apretaba el puño. Si encontraba a las personas que lo incriminaron, ¡les haría pagar!  En ese momento, Li Beini regresó con el café de todos y lo distribuyó entre todos los trabajadores. El rostro de la niña rebosaba entusiasmo. Incluso hizo comentarios de agradecimiento como: ‘¡Gracias por tu arduo trabajo!’. ¡y buena suerte!’ mientras le daba a cada persona su café.   Finalmente, se paró frente a Zhao Yu, le guiñó un ojo mientras le ponía la última taza de café delante y bajaba la voz: ‘¡Oficial Zhao, esta taza tiene dos bolsas de azúcar! Definitivamente trabajaremos horas extras esta noche. ¡Pero creo que puedes hacerlo!’  Incluso antes de que Zhao Yu mostrara alguna reacción, la niña ya se había dado la vuelta para guardar el plato, con una sonrisa en su rostro.  　 El Capitán Qu Ping había terminado de explicar el caso y se hizo a un lado para darle la palabra al Capitán Jin Zhenbang, el alto mando de la unidad de investigación. El Capitán Jin ya tenía más de cincuenta años y tenía el pelo gris salpicado. El hombre se mostraba inmensamente serio durante el trabajo y rara vez esbozaba una sonrisa.  ‘¡Básicamente, todos estarán bastante ocupados!’ El Capitán Jin habló en un tono rotundo y formal: ‘Este caso de Taser ya había ocurrido tres veces, si se cometen más delitos se convertirá en un delito en serie.",
      },
      6: {
        title: "Capitulo 6",
        contenido:
          "No podemos asumir esta responsabilidad. Debemos tratar de solucionar este caso lo más rápido posible. , así que todos por favor manténganse alerta’.  ‘Entonces el Equipo A es responsable de la recopilación de pruebas. Dado que el culpable siguió a las víctimas, debe haber aparecido en el bar que las víctimas frecuentaban. ¡Busque en todas las grabaciones de las cámaras, encuentre a esta persona! No solo eso, sino que también revise todas las cámaras. ‘Cerca del bar y de las matriculaciones de los coches. No dejes escapar ni un solo rastro de evidencia’.  ‘¡Comprendido!’ Todos los oficiales confirmaron.  ‘Equipo B, su responsabilidad recae en el contrainterrogatorio’, ordenó el Capitán Jin. ‘No tenemos datos sobre la sangre del culpable, por lo que no podemos comparar la sangre. Sin embargo, la orina del culpable es una prueba importante. Aunque no podemos encontrar ninguna coincidencia con las pruebas básicas en la estación, podemos preguntar hospitales y otros centros médicos para posibles coincidencias. ¡Siempre y cuando el culpable haya tenido un examen corporal antes, definitivamente podemos localizarlo!  ‘¡Por supuesto!’  ‘Además, la pistola Taser utilizada por el culpable, todas las señales de los teléfonos celulares dentro del área y la víctima que vio la cara de los culpables, esta evidencia no se puede ignorar. ¡Asegúrese de que la gente los revise todos!’  ‘¡Sí!’  ‘Muy bien, ahora que a cada equipo se le ha asignado su trabajo, no debería haber ningún problema. Por favor, salgan lo antes posible’. El hombre terminó su discurso y cerró sus notas, listo para darse la vuelta e irse de inmediato.  Nadie esperaba que una voz disidente se pronunciara entre la multitud.  ‘¡Espera, hay un problema!’  Todos voltearon la cabeza para ver que la fuente de la voz no era otra que Zhao Yu.  Incluso el Capitán Jin hizo una breve pausa confundido, pero preguntó con urgencia: ‘¿Qué pasa, Zhao Yu? ¿Cuál parece ser el problema?’  ‘¡A mí!’ Zhao Yu se señaló a sí mismo. ‘Me siento mal en este momento, así que me iré. Todos pueden disfrutar y cuidarse’. ",
      },
    },
    categorias: [
      {comedia: "Comedia"},
      {romance: "Romance"}
    ]
  },
  {
    id: 5,
    name: "CULTIVATION ONLINE",
    description:
      "Yuan nació con una enfermedad incurable que le dejó ciego a una edad temprana y lisiado unos años más tarde, inutilizando todo lo que tenía debajo de la cabeza. Considerado irrecuperable e irredimible, sus padres se dieron rápidamente por vencidos y el mundo le ignoró. En este mundo oscuro e inmóvil, su hermana pequeña se convirtió en su única razón para vivir. Observa cómo este joven alcanza la cima como genio en Cultivation Online, el nuevo VRMMORPG, convirtiéndose en una figura legendaria en ambos mundos.",
    categoria: "Aventura",
    image: "https://novelbin.me/media/novel/cultivation-online-novel.jpg",
    chapters: {
      1: {
        title: "Capitulo 1",
        contenido:
          "‘¡Hermano! ¡Conseguí el juego que querías! Dijo alegremente el adolescente junto al joven acostado en la cama. En su mano había un casco grande que parecía un casco de bicicleta, pero con un aspecto más de ciencia ficción.  Los ojos del joven estaban cerrados, aparentemente dormido, pero la niña continuó hablando: ‘Toma, déjame ayudarte a ponértelo…’  La niña se subió a la gran cama en la que cabía una familia entera de cuatro personas, le levantó la cabeza y le puso el casco que había preparado.  ‘Gracias…’ El joven finalmente habló con voz ronca después de que ella suavemente recostó su cabeza hacia abajo.  La niña sonrió, acariciando tiernamente su cabello para que no le molestara. ‘Hermano, aunque estaré ocupado con la escuela esta semana, la próxima semana seguro que jugaré contigo’.  ‘Naciones Unidas…’  ‘Volveré más tarde, así que hasta entonces, ¡diviértete!’ Luego de esas palabras, fue a tocar el botón en el costado del casco y esperó unos momentos antes de dejar solo al joven.  —  Solo tomó unos segundos después de presionar el botón para que el cuerpo del joven en el mundo real cayera en un estado similar al sueño. Ya no podía oler el aroma exclusivo de su habitación ni sentir el peso de la manta presionando su cuerpo. En cambio, podía sentirse de pie, algo que no tuvo la oportunidad de experimentar durante muchos años.  El mundo que tenía ante él era mayoritariamente negro, como el cielo nocturno sin estrellas, y podía ver números blancos flotando sobre él, contando lentamente.  «10:01»  «10:00»  «09:59»  ‘Puedo ver… puedo sentir mis extremidades… yo… ya no estoy ciego ni lisiado…’ El joven se derrumbó en esta oscuridad, se emocionó y cayó de rodillas.  Nació con una enfermedad incurable que lo dejó ciego a los 7 años y lisiado a los 13. Ahora tiene 18 años y durante los últimos 5 años estuvo acostado en su cama, sin poder hacer nada más que simplemente tirado ahí; Era una vida espantosa e inimaginable en la que uno ni siquiera se atrevería a imaginarse.  Sin embargo, este joven que ha pasado más de la mitad de su vida viviendo en un mundo sin luz, pudo seguir viviendo sin ceder a la desesperación gracias a su cariñosa hermana menor, quien lo apoyó todos los días sin quejarse.  ‘Así que este es el primer VRMMORPG del mundo con 100% de inmersión, eh’.  ",
      },
      2: {
        title: "Capitulo 2",
        contenido:
          "Cuando su hermana menor le habló por primera vez del juego, casi no podía creerlo.  Un juego que opera dentro de la mente del individuo, permitiéndole vivir en otro mundo sin la necesidad de mover un solo miembro. ¿Quién creería que podría existir una tecnología tan increíble y avanzada? Sin mencionar que se anunció que esta tecnología de alta tecnología era lo suficientemente asequible para que la disfrutaran incluso las familias más comunes.  Al principio era inimaginable, pero al experimentarlo de primera mano, el joven sólo puede creerlo.  «02:19»  «02:18»  La cuenta regresiva siguió bajando mientras el joven intenta familiarizarse con la sensación de mover sus extremidades. Aunque al principio fue difícil, incluso tropezando cada pocos pasos, gradualmente se fue familiarizando nuevamente con su cuerpo.  «00:03»  «00:02»  «00:01»  «00:00»  «¡Bienvenidos a Cultivación en línea!»  Cuando apareció el aviso del sistema, el espacio negro se iluminó rápidamente, convirtiéndose en una habitación blanca y brillante. Y justo delante del joven, apareció una grieta de la nada, que parecía una ventana de vidrio rota.  Grieta. Grieta. Grieta…  La grieta se hizo cada vez más grande, hasta que fue lo suficientemente grande como para que cupiera un adulto.  De repente, la gran grieta se rompió por completo, revelando la oscuridad detrás de ella, y una hermosa mujer con un cuerpo grácil y elegante salió lentamente del espacio agrietado, luciendo como una diosa que aparece de otro mundo.  ‘Esto es…’ El joven solo podía mirar aturdido mientras la hermosa mujer que acababa de salir del espacio agrietado comenzaba a mirarlo de arriba a abajo con una expresión aparentemente fría en su rostro de otro mundo. Vestida con unas túnicas rojas y doradas desconocidas, su figura era flexible y elegante. Sus rasgos faciales son nítidos, simétricos e incomparables. Considerándolo todo, parecía una diosa de otro mundo. Sin embargo, a pesar de todos sus rasgos perfectos, su mirada era todo menos amistosa.   Ella lo miró fijamente con sus ojos dorados que rebosaban un sentimiento de dominación, y su aura irradiaba un poder tiránico que el joven no podía comprender.  ‘Mortal, pon tu mano sobre esto’. La belleza le habló con una voz fría propia de un gobernante, y el joven observó mientras ella sacaba una bola de cristal de la nada.  ‘Bueno.’ ",
      },
      3: {
        title: "Capitulo 3",
        contenido:
          "Creyendo que ella era un NPC, el joven siguió sus instrucciones y colocó su mano sobre la bola de cristal sin pensarlo demasiado, y las palabras comenzaron a aparecer dentro de la bola de cristal.  Nombre: ???  Cultivo: Ninguno  Legado: Ninguno  Linaje: Ninguno  Físico: Físico refinado del cielo  Fuerza física: 34  Fuerza mental: 275  Fuerza del alma: 1,210  Defensa física: 10  Defensa Mental: 1,121  ‘¡?!?!’ La expresión de la belleza cambió repentinamente al ver la información en la bola de cristal, sus ojos claros se llenaron de incredulidad.  ‘¡Físico refinador del cielo!’ Sus manos temblaron junto con la bola de cristal que tenía en sus manos. ‘Sin mencionar que la Fuerza de su Alma está en el rango de Guerrero Espiritual a pesar de ser solo un mortal sin cultivo. ¡No, eso no es nada en comparación con su físico!’  La belleza nunca antes había estado tan sorprendida, incluso hasta el punto de que su cuerpo temblara.  ‘¿Hay algo mal?’ Le preguntó el joven al ver su silencio y expresión emocionada.  Levantó la cabeza para mirarlo y pensó para sí misma: ‘Debo obligarlo a unirse a mi facción antes de que los demás lo encuentren...’  ‘¿Cómo te llamas?’ ella le preguntó con una expresión seria.  ‘Puedes llamarme Yuan’.  ‘Toma esta ficha y guárdala contigo hasta que nos veamos la próxima vez’. La belleza recuperó un medallón de jade de la nada y de repente se lo arrojó. ‘No me queda mucho tiempo aquí. Asegúrate de no perder la ficha, te veré de nuevo’.  ‘¿Eh? Espera, tengo algunos…’ Antes de que Yuan pudiera siquiera hacerle alguna pregunta, la belleza regresó al agujero agrietado, desapareciendo junto a la grieta en el aire.  ‘Qué PNJ más extraño. ¿Qué debería hacer ahora?’ Miró alrededor del lugar vacío.  «Evaluación del personaje completa. La teletransportación ocurrirá en 10 segundos.»  «00:02»  «00:01»  Cuando el cronómetro llegó a cero, la visión de Yuan de repente se torció, provocándole un ligero dolor de cabeza. ",
      },
      4: {
        title: "Capitulo 4",
        contenido:
          "Cuando parpadeó y abrió los ojos, se encontró en una especie de escenario donde muchas personas que vestían la misma túnica blanca que él estaban reunidas en un área espaciosa.  ‘¿Esto es… Cultivo en Línea?’ Sus ojos se abrieron cuando vio montañas flotando en el cielo sobre las nubes y lo que parecían ser casas construidas sobre estas montañas flotantes.  ‘¡Bienvenidos, mortales! Soy el élder Song, a cargo de asegurarme de que antes de que todos abandonen este lugar y se aventuren en este vasto mundo, tengan en mente el objetivo de lo que quieren hacer aquí’. Un anciano con túnica azul de repente saludó a todos con una voz resonante, haciendo que todos los presentes miraran por encima de ellos.  ‘¡Está volando! ¡Realmente está volando mientras está parado sobre esa espada! El pueblo exclamó lo obvio.  El élder Song sonrió y dijo: ‘Responderé a sus preguntas más tarde, pero primero, déjeme explicarle sobre este mundo: el mundo del Cultivo’.  ‘En primer lugar, este es el Continente Celestial, y actualmente estamos en la Montaña #96. Antes de ser transportado aquí, todos deberían haber conocido a un representante de nuestro mundo que les hiciera una evaluación. Ese es el estatus de tu personaje; te dice casi todo sobre ti mismo’.  ‘Comenzaremos con lo básico. En este mundo, los humanos y los monstruos cultivan sus cuerpos y mentes con Spirit Qi que les permite obtener poderes sobrenaturales. Llamamos a personas como ellos Cultivadores, y cuanto mayor sea el nivel de cultivo que alcances, más fuerte serás en este mundo. Legacy y Bloodlines son características especiales que se pueden obtener más adelante si tienes la suerte. En cuanto a Physique, todos aquí deberían tener uno. Si es inútil o no, esto te lo dirá’.  El élder Song agitó sus mangas largas y miles de talismán volaron hacia la gente allí.   ‘Actívalo con tus pensamientos’, dijo el élder Song.  La multitud siguió sus instrucciones y poco después resonaron fuertes exclamaciones.  ",
      },
      5: {
        title: "Capitulo 5",
        contenido:
          " ‘¡Dice que tengo un físico clasificado como el de la Tierra! ¿Qué significa eso?’  El élder Song miró al joven que acababa de hablar y le dijo: ‘Hay una probabilidad entre diez mil de que uno nazca con un físico de rango terrestre. Felicidades. Eres lo que llamamos 'talentoso'‘.  ‘Anciano, ¿cuántos rangos de físicos hay?’  ‘El rango de Físicos consiste en Mortal, Tierra, Cielo y Divino’.  ‘Anciano, ¿qué significa tener un físico de rango mortal y cuál es la diferencia entre los rangos?’  El élder Song permaneció en silencio por un momento, antes de hablar con una sonrisa: ‘Tener un físico mortal significa que eres normal, pero tener un físico terrestre significa que tienes talento. La diferencia es obvia: ¡eres naturalmente inferior a aquellos que tienen mejor físico que tú! ¡Cuanto más talento tengas, más fácil te resultará como Cultivador!  Sus palabras hicieron que muchos rostros se hundieran, especialmente aquellos con un Físico Mortal.  ‘¿Se pueden cambiar nuestros físicos?’ Alguien preguntó de repente.  ‘El físico se puede cambiar, pero el proceso es largo y doloroso, por lo que la mayoría de la gente simplemente acepta su destino’.  La gente suspiró aliviada al escuchar que su Físico Mortal se puede cambiar.  ‘¿Alguien aquí tiene un físico de rango divino?’ Los ojos del élder Song parpadearon con expectación, pero cuando nadie respondió a su pregunta, la luz de sus ojos se atenuó.  ‘Las posibilidades de que alguien tenga un Físico Divino son una entre cien millones, un genio por encima del genio que no conoce igual, por lo que no es sorprendente que tal prodigio no aparezca entre apenas mil personas’. Sacudió la cabeza para sus adentros.  ‘Anciano, tengo un físico clasificado como el Cielo’. Un individuo dijo de repente en voz alta, haciendo que todos los presentes lo miraran.  ‘¿Eh? Las posibilidades de que aparezca un Heaven Physique son una entre un millón. Eres muy afortunado, joven genio. ¿Cómo te llamas?’  ‘Mi nombre es Shen Ming’, respondió el apuesto joven.  ‘¿Shen Ming? ¿No es él el hijo mayor de Shen Li, el director ejecutivo de Royal Entertainment?  ",
      },
      6: {
        title: "Capitulo 6",
        contenido:
          "Algunas personas reconocieron al apuesto joven cuyo rostro se veía exactamente igual al de la vida real.  ‘¿Recibiste algo del representante que hizo tu evaluación?’ El élder Song le preguntó con gran interés.  ‘Sí, lo hice.’ Shen Ming no ocultó ese hecho y le dijo la verdad. ‘Recibí esta bolsa del representante’.  ‘Oho… Esa es una bolsa de almacenamiento que se usa para guardar artículos, puede que haya algunas cosas allí que podrían beneficiarte. Sin embargo, sólo los cultivadores son capaces de utilizarlo. Además, si puedes volver a encontrarte con la persona que te dio ese regalo, es posible que incluso te reclute como discípulo de su Secta’.  ‘¿Secta? ¿Te refieres a gremios?  ‘Una Secta es un lugar creado por uno o un grupo de personas con el propósito de nutrir a sus discípulos para que se conviertan en Cultivadores poderosos; básicamente, una escuela para Cultivadores’. El élder Song explicó brevemente. ‘¿Es asi? ¿Nadie más tiene un Heaven Physique?  Después de un momento de silencio, el élder Song sacudió la cabeza y pensó para sí mismo: ‘Qué lástima que solo haya una persona entre las miles aquí en la que valga la pena invertir. Pero incluso entonces, no sé quién le había dado ese almacenamiento’. bolsa. Sería grosero de mi parte si le robara su objetivo, e incluso podría ofender a alguien a quien no puedo permitirme el lujo de ofender.  ‘Tengo una pregunta para todos aquí antes de dejarlos ir… ¿Qué desean lograr en este mundo? ¿Fortaleza? ¿Estado? ¿Poder? ¿Hombre guapo? ¿Mujer hermosa? ¡Dime, Mortales de otro mundo!  ‘¡Quiero volar como tú!’  ‘¡Deseo poder!’  ‘¡Quiero ser famoso!’  ‘¡Quiero suficiente dinero para hacer una montaña!’  ‘¡Quiero caminar con mujeres hermosas en ambos brazos!’  ‘¡Quiero que hombres guapos me mimen!’   El élder Song sonrió al escuchar los deseos de las masas. ‘¡Si quieres sobrevivir en un mundo como este, entonces debes tener poder! ¡En este mundo, los fuertes gobiernan a los débiles! ¡La riqueza y la fama vendrán naturalmente si eres fuerte! ¡La gente acudirá a ti si eres fuerte! Recuerden mis palabras, jóvenes: ¡este mundo menosprecia a los débiles y a los inferiores, respetando sólo a los fuertes! ¡Tener fuerza significa que lo tienes todo!  ‘¿Quién crees que tiene más poder en este mundo?’ ",
      },
      7: {
        title: "Capitulo 7",
        contenido:
          "El élder Song miró a las personas de abajo con los ojos entrecerrados, provocando escalofríos por su columna vertebral.  ‘¡Cultivadores! Nosotros, los Cultivadores, somos un símbolo de poder, riqueza, fama y respeto: ¡somos el gobierno de este mundo!  ‘Cultivadores, ¿es eso algún tipo de clase?’ La gente se preguntó.  ‘Anciano, ¿cómo puedo convertirme en Cultivador?’  El élder Song sonrió. ‘Es realmente simple’. De repente agitó sus mangas y miles de orbes brillantes aparecieron de la nada y volaron hacia las personas y directamente a sus frentes, sumergiéndose en sus cerebros.  ‘Acabo de darte todo el método para cultivarte. Ahora depende de ti decidir si quieres cultivarte o permanecer como mortal’. El élder Song volvió a agitar sus mangas y cuatro portales aparecen no muy lejos del grupo. ‘Cada portal representa un continente. En este mundo, tenemos cuatro grandes continentes sin incluir este continente celestial. Una vez que entres, te llevará a un lugar dentro de uno de estos Cuatro Grandes Continentes al azar, pero ni siquiera yo sabré exactamente dónde aterrizarás, así que depende de tu destino’.  «Has aprendido: Técnica básica de recolección de Qi»  «Rango: Mortal»  «Nivel de maestría: 1»  «Descripción: Absorbe 1 Qi cada segundo. Sólo se puede activar estando sentado en posición de loto.»  ‘Ahora, lárgate. He pasado demasiado de mi precioso tiempo tratando con ustedes, mortales. Aprenderá más sobre este mundo a medida que viaje. Incluso si uso el resto de mi longevidad, no podré explicarte todo sobre este mundo’.  Con otro movimiento de su manga, todos los presentes comenzaron a volar hacia el portal como si fueran atraídos hacia ellos.  ‘¡¡¡Ahhhh!!!’  Resonaron gritos de sorpresa y aquellos que entraron al portal pronto aparecerían al azar en este vasto y desconocido mundo.  —  Después de ser arrojado al portal, Yuan volvió a sentir un ligero mareo y, antes de darse cuenta, estaba en medio de un bosque.  ‘¿Donde está esto? ¿Hay algún mapa que pueda usar?  De repente, aparece ante él un gran mapa con cuatro grandes continentes separados por agua.  ‘¿Continente Oriental?’ Esa fue la única información que pudo obtener del mapa. Todo lo demás estaba tachado.  Yuan inclinó la cabeza para mirar el cielo brillante y suspiró. ‘No pude preguntarle sobre mi físico.",
      },
    },
    categorias: [
      {aventura: "Aventura"},
      {romance: "Romance"}
    ]
  },
];

app.get("/", (req, res) => {
  res.send("Node JS api Novelas");
});

app.get("/api/novelas", (req, res) => {
  res.send(novelas);
});

app.post("/api/novelas", (req, res) => {
  const novela = {
    id: novelas.length + 1,
    name: req.body.name,
    description: req.body.description,
    image: req.body.image,
    chapters: {
      1: {
        title: req.body.chapters[1].title,
        contenido: req.body.chapters[1].contenido,
      },
    },
  };
  novelas.push(novela);
  res.send(novela);
});

app.delete("/api/novelas", (req, res) => {
  const novela = novelas.find(c.id == parseInt(req.params.id));
  if (!novelas) return res.status(400).send("Novela no encontrada");

  const index = novelas.indexOf(novela);
  novelas.splice(index, 1);
  res.send(novela);
});

app.post("/api/novelas/:id/capitulos", (req, res) => {
  const novelaId = parseInt(req.params.id);
  const nuevoCapitulo = {
    title: req.body.title,
    contenido: req.body.contenido,
  };
  if (!nuevoCapitulo.title || !nuevoCapitulo.contenido) {
    return res.status(400).json({
      error: "Se requieren título y contenido para el nuevo capítulo",
    });
  }
  const novela = novelas.find((n) => n.id === novelaId);
  if (!novela) {
    return res.status(404).json({ error: "Novela no encontrada" });
  }
  const nuevoNumeroCapitulo = Object.keys(novela.chapters).length + 1;
  novela.chapters[nuevoNumeroCapitulo] = nuevoCapitulo;

  res
    .status(201)
    .json({ message: "Capítulo añadido con éxito", capitulo: nuevoCapitulo });
});

const port = process.env.port || 80;
app.listen(port, () => console.log(`Escuchando en puerto ${port}...`));
